#!/usr/bin/env php
<?php
// application.php

require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;

$container = new \Symfony\Component\DependencyInjection\ContainerBuilder();
$loader = new \Symfony\Component\DependencyInjection\Loader\YamlFileLoader($container, new \Symfony\Component\Config\FileLocator(__DIR__.'/src/Resources/config'));
$loader->load('services.yml');

// Commands
$addCommand = new \Hints\Command\AddCommand();
$addCommand->setContainer($container);

$showCommand = new \Hints\Command\ShowCommand();
$showCommand->setContainer($container);

$application = new Application('Hints', '1.0');

$application->add($addCommand);
$application->add($showCommand);
$application->setDefaultCommand($showCommand->getName());

$application->run();